// <auto-generated />
namespace Coffee0417.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create1026 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create1026));
        
        string IMigrationMetadata.Id
        {
            get { return "202110260522424_create1026"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
